name: 'Update data'

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Update data
        run: |
          npm run build
          git config user.name 'Tibia Auth Bot'
          git config user.email 'contact@tibia-auth.com'
          date=$(date +'%Y-%m-%d-%H-%M')
          git add data
          git commit data -m "Add data for date=${date}" || true
          git push
